### ISSUE TITLE
Podcast 1.4.1

### ISSUE THREAD

**Issue by eduncan911** [floge77/cloud2podcast#2]
Just FYI, I noticed you using my `podcast` package.  I've since merged a bunch of community updates and improved some underlying code for better feed compatibility.

Just saying, there's a newer version available.  :)

There's no breaking changes between 1.3.0 and 1.4.1.

**Comment by floge77** [comment]
Hi @eduncan911 

thanks a lot for reaching out! 
I will update soon.

**Comment by eduncan911** [comment]
Nice. 1.4.2 has a slimmer `go module` scope.  :)
